#!/usr/bin/env bash

git config --global core.fileMode false

docker image pull sensukho/mg2-stack

cp docker-compose-dis.yml docker-compose.yml
sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml;

if [ ! -d src ]; then
  mkdir src;
  echo "<?php phpinfo();" > src/index.php;
fi

echo "sudo chmod -R u+x ./*"
sudo chmod -R u+x ./*

bash start