#!/usr/bin/env bash

git config --global core.autocrlf false
git config --global core.eol LF
git config --global core.fileMode false
git config --global diff.renamelimit 5000

sudo chmod -R u+x ./*

docker image pull sensukho/mg2-stack

if [ "$(uname)" == "Darwin" ]; then
    git checkout -f mac;
    sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml \
    && sed -i '' -e "s/<project_name>/$1/g" docker-compose-dev.yml \
    && sed -i '' -e "s/<project_name>/$1/g" docker-sync.yml;
elif [ "$(uname)" == "cygwin" ] || [ "$(uname)" == "msys" ] || [ "$(uname)" == "win32" ]; then
    git checkout -f windows;
    sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml \
    && sed -i '' -e "s/<project_name>/$1/g" docker-compose-dev.yml \
    && sed -i '' -e "s/<project_name>/$1/g" docker-sync.yml;
else
    git checkout -f master;
    sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml;
fi

if [ ! -e src/index.php ]; then
  echo "<?php phpinfo();" > src/index.php;
fi

if [ -d src/app/etc ]; then  
  if [ ! -e src/app/etc/env.php ]; then
    cp .docker/users/env.sample.php src/app/etc/env.php;
  fi
fi

chmod -R 777 src

bash start
