#!/usr/bin/env bash

git config --global core.fileMode false

sudo chmod -R u+x ./*

docker image pull sensukho/mg2-stack:v1

cp docker-compose-dis.yml docker-compose.yml
cp install-dist install
sed -i -e "s/<project_name>/$1/g" docker-compose.yml;
sed -i -e "s/<project_name>/$1/g" install;

if [ ! -d src ]; then
  mkdir src;
  echo "<?php phpinfo();" > src/index.php;
fi

sudo chmod -R 777 src

make start
